# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ciat}
  s.version = "0.4.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy D. Frens", "Mark Van Holstyn"]
  s.date = %q{2009-10-09}
  s.description = %q{CIAT (pronounced "dog") is a library of Ruby and rake code to make writing acceptance tests for compilers and interpreters easier (despite their implementation, source, and target languages).}
  s.email = %q{jdfrens@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/ciat.rb",
     "lib/ciat/cargo.rb",
     "lib/ciat/compilers/java.rb",
     "lib/ciat/crate.rb",
     "lib/ciat/differs/html_differ.rb",
     "lib/ciat/erb_helpers.rb",
     "lib/ciat/executors/java.rb",
     "lib/ciat/executors/parrot.rb",
     "lib/ciat/feedback/composite.rb",
     "lib/ciat/feedback/feedback_counter.rb",
     "lib/ciat/feedback/html_feedback.rb",
     "lib/ciat/feedback/return_status.rb",
     "lib/ciat/feedback/standard_output.rb",
     "lib/ciat/processors/basic_processing.rb",
     "lib/ciat/processors/compilation_interpreter.rb",
     "lib/ciat/processors/compiler.rb",
     "lib/ciat/processors/copy.rb",
     "lib/ciat/processors/interpreter.rb",
     "lib/ciat/rake_task.rb",
     "lib/ciat/suite.rb",
     "lib/ciat/test.rb",
     "lib/ciat/test_element.rb",
     "lib/ciat/traffic_light.rb",
     "lib/ciat/version.rb"
  ]
  s.homepage = %q{http://github.com/jdfrens/ciat}
  s.rdoc_options = ["--charset=UTF-8", "--title", "CIAT -- Compiler and Interpreter Acceptance Tester", "--main", "README.txt", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Acceptance tester for compilers and interpreters}
  s.test_files = [
    "spec/ciat/cargo_spec.rb",
     "spec/ciat/compilers/java_spec.rb",
     "spec/ciat/crate_spec.rb",
     "spec/ciat/erb_helpers_spec.rb",
     "spec/ciat/executors/java_spec.rb",
     "spec/ciat/executors/parrot_spec.rb",
     "spec/ciat/feedback/composite_spec.rb",
     "spec/ciat/feedback/feedback_counter_spec.rb",
     "spec/ciat/feedback/html_feedback_spec.rb",
     "spec/ciat/feedback/return_status_spec.rb",
     "spec/ciat/feedback/standard_output_spec.rb",
     "spec/ciat/processors/basic_processing_spec.rb",
     "spec/ciat/suite_spec.rb",
     "spec/ciat/test_element_spec.rb",
     "spec/ciat/test_spec.rb",
     "spec/ciat/traffic_light_spec.rb",
     "spec/ciat_spec.rb",
     "spec/spec_helper.rb",
     "spec/templates/detail_row/elements_html_erb_spec.rb",
     "spec/templates/detail_row_html_erb_spec.rb",
     "spec/templates/elements/diff_html_erb_spec.rb",
     "spec/templates/elements/plain_element_html_erb_spec.rb",
     "spec/templates/report_html_erb_spec.rb",
     "spec/templates/summary_row_html_erb_spec.rb",
     "spec/templates/test_numbers_html_erb_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
