$:.unshift(File.join(File.dirname(__FILE__), "..", "lib"))

require 'fileutils'

require 'ciat'
require 'ciat/compilers/java'
require 'ciat/compilers/copy'
require 'ciat/executors/cat'
require 'ciat/executors/parrot'

desc "Cleans the output directory, compiles the Java code, runs tests"
task :default => [:clean_start, :compile_java,
                  :simple, :java_cat, :java_parrot, :failures] do
  check_output_files
end

task :compile_java do
  unless system("cd java ; javac *.java")
    raise Exception.new
  end
end

task :clean_start do
  FileUtils.rm_r("temp/") if File.exists?("temp/")
end

task :simple do
  puts "Copy compiler, cat executor"
  CIAT::Suite.new(copy_compiler, cat_executor,
    :files => ['ciat/copy-cat.ciat'],
    :feedback => FeedbackTester.new(1)).run
end
  
task :java_cat do
  puts "Java compiler, cat executor, special folder"
  CIAT::Suite.new(java_compiler("Hello"), cat_executor,
    :folder => 'ciat/java-cat',
    :report_filename => 'java-cat.html',
    :feedback => FeedbackTester.new(1)).run
end

task :java_parrot do
  puts "Java compiler, Parrot executor, special folder"
  CIAT::Suite.new(java_compiler("Parrot5"), parrot_executor,
    :folder => 'ciat/java-parrot',
    :report_filename => 'java-parrot.html',
    :feedback => FeedbackTester.new(1)).run  
end

task :failures do
  puts "Failed compilation"
  CIAT::Suite.new(java_compiler("Failing"), ExceptionalExecutor.new,
    :files => 'ciat/failures/failed-compile.ciat',
    :report_filename => 'failed-compiler.html',
    :feedback => FeedbackTester.new(1)).run
  puts "Wrong compilation"
  CIAT::Suite.new(copy_compiler, ExceptionalExecutor.new,
    :files => 'ciat/failures/bad-compile.ciat',
    :report_filename => 'bad-compile.html',
    :feedback => FeedbackTester.new(1)).run
  puts "Failed execution"
  CIAT::Suite.new(copy_compiler, FailingExecutor.new,
    :files => 'ciat/failures/failed-execution.ciat',
    :report_filename => 'failed-execution.html',
    :feedback => FeedbackTester.new(1)).run
  puts "Wrong execution"
  CIAT::Suite.new(copy_compiler, cat_executor,
    :files => 'ciat/failures/wrong-execution.ciat',
    :report_filename => 'wrong-execution.html',
    :feedback => FeedbackTester.new(1)).run
end

#
# Compilers & Executors
#
def copy_compiler
  CIAT::Compilers::Copy.new
end

def java_compiler(type)
  CIAT::Compilers::Java.new('./java', type + 'Compiler')
end

def cat_executor
  CIAT::Executors::Cat.new
end

def parrot_executor
  CIAT::Executors::Parrot.new
end

class ExceptionalExecutor
  def execute(x,y)
    raise("**** should not run this executor!!!")
  end
end

class FailingExecutor
  def execute(x, output_file)
    system("echo this should be the error output > #{output_file}")
    false
  end
end

#
# Output file checking
#
def check_output_files
  puts "Checking output files."
  unless system("diff -r temp_expected/ temp/")
    raise("**** diff failed!")
  end
end

#
# Feedback from running suite
#
class FeedbackTester
  def initialize(size)
    @size = size
  end
  
  def post_tests(suite)
    puts "*** Wrong number of tests: #{@size} expected, got #{suite.size}" unless suite.size == @size
  end
end
